export const RELLENAR_CATEGORIAS = 'RELLENAR_CATEGORIAS';
export const OBTENER_FRASE = 'OBTENER_FRASE';
export const AGREGAR_FRASE = 'AGREGAR_FRASE';
export const CARGAR_FRASES = 'CARGAR_FRASES';
export const BORRAR_FRASE = 'BORRAR_FRASE';

